### 1.Create a python program to find duplicate files by content. User will input path and it will scan all directories, sub-directories to find all duplicates files.
Delete the found duplicate file.
[Hint: use hashlib]


In [1]:
import os
import hashlib
d_path = 'D:/file/'
files_list = os.listdir(path = d_path)
files_list

['text1.txt', 'text2.txt']

In [2]:
list1=[]
for i in files_list:
    obj_f=open(d_path+i,'r')
    content = obj_f.read()
    obj_f.close()
    encode_content = content.encode()
    list1.append(hashlib.sha256(encode_content).hexdigest())

In [3]:
new_dict = dict(zip(files_list,list1))
new_dict

{'text1.txt': '3a038375ff866e6d29f52be206cb1ecd0e93a962f4f89a2a7b2433aeaa8e91c1',
 'text2.txt': '3a038375ff866e6d29f52be206cb1ecd0e93a962f4f89a2a7b2433aeaa8e91c1'}

In [4]:
type(new_dict.values())

dict_values

In [5]:
list1

['3a038375ff866e6d29f52be206cb1ecd0e93a962f4f89a2a7b2433aeaa8e91c1',
 '3a038375ff866e6d29f52be206cb1ecd0e93a962f4f89a2a7b2433aeaa8e91c1']

In [6]:
for i in range(len(list1)):
    if list1[i]==list1[i+1]:
        print(True)
    else:
        print(False)

True


IndexError: list index out of range

In [7]:
for i in new_dict:
    file2 = i
    new_path = os.path.join(d_path,file2)
    print(new_path)
    os.remove(new_path)

D:/file/text1.txt
D:/file/text2.txt


### 2.Generate random Password with exact length = 6, with minimum 1 uppercase, 2 lowercase, 2 digits, and remaining special characters.
Using these packages [random, strings]


In [2]:
import random
import string

def generate_password():

    uppercase = string.ascii_uppercase
    lowercase = string.ascii_lowercase
    digits = string.digits
    special = string.punctuation
    
    
    uppercase_chars = random.sample(uppercase, 1)
    lowercase_chars = random.sample(lowercase, 2)
    digit_chars = random.sample(digits, 2)
   

    password_chars = uppercase_chars + lowercase_chars + digit_chars
    remaining_chars = ''.join(random.sample(special, 1))
    password_chars.append(remaining_chars)
    random.shuffle(password_chars)
    
   
    password = ''.join(password_chars)
    return password

In [3]:
generate_password()

'fqP3~6'

### 3.Create 2D array and update the same 2D array provided that every prime number position should be replaced by cube of the positioned number.

In [13]:
import numpy as np
import sympy
arr1=np.arange(0,9).reshape(3,3)
shape = arr1.reshape(9)
print(shape)
for i in range(len(shape)):
    if sympy.isprime(shape[i]):
        shape[i]=shape[i]**3
        
new=shape.reshape(3,3)
print(new)

[0 1 2 3 4 5 6 7 8]
[[  0   1   8]
 [ 27   4 125]
 [  6 343   8]]


### 4.Python program to get the sum of every cubed value and its previous integer. 

In [8]:
import numpy as np
import sympy
prime = []
arr1=np.arange(0,9).reshape(3,3)
shape = arr1.reshape(9)
for i in range(len(shape)):
    if sympy.isprime(shape[i]):
        shape[i]=shape[i]**3
        shape[i]=shape[i] + shape[i-1]
        
new_shape=shape.reshape(3,3)
print(new_shape)

[[  0   1   9]
 [ 36   4 129]
 [  6 349   8]]


### 5.Given two arrays, find their intersection. Examples:

In [6]:
# Function to find intersection of two arrays

def interSection(arr1,arr2):

    result = list(filter(lambda x: x in arr1, arr2))
    print ("Intersection : ",result)

# Driver program
if __name__ == "__main__":
    arr1 = [1, 3, 4, 5, 7]
    arr2 = [2, 3, 5, 6]
    interSection(arr1,arr2)


Intersection :  [3, 5]


### 6.Create a 7 x 7  2D array having only multiples of 7. And return the last element of the same.

In [12]:
x=np.array([i*7 for i in range(1,7*7+1)]).reshape(7,7)
x[-1,-1]

343

### 7.Checker Board Patten using Numpy:


In [9]:
import numpy as np
arr1=np.ones((5,7))
# start postion : step size
arr1[1::2,0::2]=0
arr1[0::2,1::2]=0
arr1

array([[1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1.]])

### 8.	Create a given Matrix:

In [10]:
import numpy as np
arr = np.array([['A','B','C','D'],
                ['E','F','G','H'],
                ['I','J','K','L'],
                ['M','N','O','P'],
                ['Q','R','S','T'],
                ['U','V','W','X']]
)

In [11]:
lis = arr.tolist()
for i in range(len(lis)):
    for j in range(len(lis[i])):
        if lis[i][j]=='A' or lis[i][j]=='E' or lis[i][j]=='I' or lis[i][j]=='O' or lis[i][j]=='U':
             lis[i][j] = np.nan
                
print(np.array(lis)) 

[['nan' 'B' 'C' 'D']
 ['nan' 'F' 'G' 'H']
 ['nan' 'J' 'K' 'L']
 ['M' 'N' 'nan' 'P']
 ['Q' 'R' 'S' 'T']
 ['nan' 'V' 'W' 'X']]
